export const ISSUE_CODES = {
  XSD_PARSE_ERROR: "XSD_PARSE_ERROR",

  DUPLICATE_GLOBAL_ELEMENT: "DUPLICATE_GLOBAL_ELEMENT",
  DUPLICATE_GLOBAL_COMPLEX_TYPE: "DUPLICATE_GLOBAL_COMPLEX_TYPE",
  DUPLICATE_GLOBAL_SIMPLE_TYPE: "DUPLICATE_GLOBAL_SIMPLE_TYPE",
  DUPLICATE_GLOBAL_ATTRIBUTE: "DUPLICATE_GLOBAL_ATTRIBUTE",
  DUPLICATE_GLOBAL_GROUP: "DUPLICATE_GLOBAL_GROUP",
  DUPLICATE_GLOBAL_ATTRIBUTE_GROUP: "DUPLICATE_GLOBAL_ATTRIBUTE_GROUP",

  UNKNOWN_TYPE: "UNKNOWN_TYPE",
  UNKNOWN_REF: "UNKNOWN_REF",
  UNKNOWN_GROUP: "UNKNOWN_GROUP",
  UNKNOWN_ATTRIBUTE_GROUP: "UNKNOWN_ATTRIBUTE_GROUP",
  MISSING_BASE_TYPE: "MISSING_BASE_TYPE",

  UNSUPPORTED_FEATURE: "UNSUPPORTED_FEATURE",

  INVALID_OCCURS_RANGE: "INVALID_OCCURS_RANGE",
  INVALID_DEFAULT_FIXED_COMBINATION: "INVALID_DEFAULT_FIXED_COMBINATION",

  XML_PARSE_ERROR: "XML_PARSE_ERROR",
  XML_ROOT_ELEMENT_MISMATCH: "XML_ROOT_ELEMENT_MISMATCH",
  XML_UNKNOWN_ROOT_ELEMENT: "XML_UNKNOWN_ROOT_ELEMENT",
  XML_UNEXPECTED_ELEMENT: "XML_UNEXPECTED_ELEMENT",
  XML_MISSING_REQUIRED_ELEMENT: "XML_MISSING_REQUIRED_ELEMENT",
  XML_CHOICE_NOT_SATISFIED: "XML_CHOICE_NOT_SATISFIED",
  XML_ALL_MISSING_REQUIRED_ELEMENT: "XML_ALL_MISSING_REQUIRED_ELEMENT",
  XML_UNEXPECTED_ATTRIBUTE: "XML_UNEXPECTED_ATTRIBUTE",
  XML_MISSING_REQUIRED_ATTRIBUTE: "XML_MISSING_REQUIRED_ATTRIBUTE",
  XML_INVALID_TEXT_FOR_COMPLEX_TYPE: "XML_INVALID_TEXT_FOR_COMPLEX_TYPE",
  XML_VALUE_INVALID: "XML_VALUE_INVALID",
  XML_ENUMERATION_MISMATCH: "XML_ENUMERATION_MISMATCH",

  XML_PATTERN_MISMATCH: "XML_PATTERN_MISMATCH",
  XML_LENGTH_MISMATCH: "XML_LENGTH_MISMATCH",
  XML_MIN_LENGTH_VIOLATION: "XML_MIN_LENGTH_VIOLATION",
  XML_MAX_LENGTH_VIOLATION: "XML_MAX_LENGTH_VIOLATION",
  XML_MIN_INCLUSIVE_VIOLATION: "XML_MIN_INCLUSIVE_VIOLATION",
  XML_MAX_INCLUSIVE_VIOLATION: "XML_MAX_INCLUSIVE_VIOLATION",
  XML_MIN_EXCLUSIVE_VIOLATION: "XML_MIN_EXCLUSIVE_VIOLATION",
  XML_MAX_EXCLUSIVE_VIOLATION: "XML_MAX_EXCLUSIVE_VIOLATION",
  XML_TOTAL_DIGITS_VIOLATION: "XML_TOTAL_DIGITS_VIOLATION",
  XML_FRACTION_DIGITS_VIOLATION: "XML_FRACTION_DIGITS_VIOLATION",

  XSD_LENGTH_CONFLICT: "XSD_LENGTH_CONFLICT",
  XSD_NUMERIC_RANGE_CONFLICT: "XSD_NUMERIC_RANGE_CONFLICT",
  XSD_DIGITS_INVALID: "XSD_DIGITS_INVALID",
  XSD_DIGITS_CONFLICT: "XSD_DIGITS_CONFLICT",
  XSD_ENUM_DUPLICATE: "XSD_ENUM_DUPLICATE",
  XSD_PATTERN_INVALID: "XSD_PATTERN_INVALID",
  XSD_FACET_NOT_ALLOWED: "XSD_FACET_NOT_ALLOWED"
};